### PR TITLE
Code review of #4

### LINKED ISSUE #4: Code review and documentation:  load_map
The following functions could use checking/review and documentation (including @importFrom declarations etc):

  hs_data_dir
  hs_cache_dir
  download_maps
  read_map
  load_map

### PR DESCRIPTION
**Pull request by CGMossa**
Fixes #4 

- [x] `hs_data_dir`
- [x] `hs_cache_dir`
- [x] `download_maps`
- [x] `read_map`
- [x] `load_map`

Extra files reviewed:
- [x] `all_nuts_codes`

### CODE REVIEW

**Comment by CGMossa** [comment]
@mdenwood The `read_map` function only uses `hs_data_dir`. Is that intentional? What about `hs_cache_dir`?

**Review by mdenwood — APPROVED** [review]
I see you are a :: fan - I tend not to use it within packages (I vaguely remember something about symbol resolution somehow being slower that way - although can't find a reference now) but can be persuaded! Let's discuss later.

**Comment by mdenwood** [comment]
> @mdenwood The `read_map` function only uses `hs_data_dir`. Is that intentional? What about `hs_cache_dir`?

@CGMossa  The cache dir will only be used by load_corine (as there is no significant computational bottleneck with read_map). Perhaps we can look at a cache within the package namespace for load_map if we want a speedup there.

I'm also going to remove the hs_data_dir and hs_cache_dir functions from the namespace for now, in case we want to change them.

**Comment by CGMossa** [comment]
Yes! I did not see the need for them to be exported, but I thought that was a silly question.

Perfect!

**Pull request merged**
